
export const CHECK_VALIDATION = 'CHECK_VALIDATION';
export const SET_TEXT = 'SET_TEXT';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const CANCEL_PICTURE = 'CANCEL_PICTURE';
export const APPLY_ADVERT = 'APPLY_ADVERT';
export const DELETE_ADVERT = 'DELETE_ADVERT';
export const EDIT_ADVERT = 'EDIT_ADVERT';
export const FINISH_ACTION = 'FINISH_ACTION';
